packages:
  - .
  - packages/tylant/packages/*
  - '!**/test/**'
onlyBuiltDependencies:
  - esbuild
  - sharp
overrides:
  '@myriaddreamin/typst-ts-node-compiler': npm:@wybxc/typst-ts-node-compiler@0.7.1
  '@myriaddreamin/typst-ts-renderer': npm:@wybxc/typst-ts-renderer@0.7.1
  '@myriaddreamin/typst.ts': npm:@wybxc/typst.ts@0.7.1
patchedDependencies:
  astro-typst@0.12.3: patches/astro-typst@0.12.3.patch
