name: Test Build (No Deployment)

on:
  # Runs on pushes targeting test branches
  push:
    branches: 
      - "test/*"
      - "feature/*"
      - "fix/*"
      - "copilot/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read

# Allow only one concurrent test build
concurrency:
  group: "test-build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      TYPST_FONT_PATHS: assets/fonts
      TYPST_FONT_PATH: assets/fonts
      BLOG_FONT_DIR: assets/fonts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Git for submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive || echo "Some submodules failed to initialize, continuing..."
          # Work around mathyml submodule issue
          if [ ! -d "typ/packages/mathyml" ]; then
            mkdir -p typ/packages/mathyml
            echo "# Placeholder for mathyml" > typ/packages/mathyml/README.md
          fi
      
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      
      - name: Download Fonts
        run: |
          mkdir -p ./assets/fonts
          curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.1.5/source-han-serif-font-assets.tar.gz | tar -xvz -C assets/fonts
          curl -L https://raw.githubusercontent.com/stipub/stixfonts/master/zipfiles/static_otf.zip -o assets/fonts/static_otf.zip
          unzip -o -j assets/fonts/static_otf.zip -d assets/fonts
          rm assets/fonts/static_otf.zip
          ls ./assets/fonts

      - run: pnpm install
      
      - name: Test Build
        run: |
          echo "=== Font paths debugging ==="
          echo "Assets fonts:"
          ls -la ./assets/fonts/ || echo "No assets/fonts directory"
          echo "Public fonts:"
          ls -la ./public/fonts/ || echo "No public/fonts directory"
          echo "Environment variables:"
          env | grep -i font || echo "No font environment variables set"
          
          echo "=== Running build ==="
          pnpm build
        
      - name: Build Success
        run: echo "✅ Build completed successfully!"